name: "Docs and Reports"
on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**.sh'
    - '**.py'
    - '**.css'
    - '**Doxyfile'
    - '**doxyignore'
    - 'keywords.txt'
    - '**docs_and_reports.yml'
  pull_request:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**.sh'
    - '**.py'
    - '**.css'
    - '**Doxyfile'
    - '**doxyignore'
    - 'keywords.txt'
    - '**docs_and_reports.yml'
jobs:
  build:
    name: "Docs and Reports"
    runs-on: ubuntu-latest
    
    env:
      REQUIRED_LIBRARIES: FastLED
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
     
      - name: Generate Documentation
        uses: langroodi/doxygenize@v1.3
        with:
          doxygenconf: './extras/Doxyfile'
          htmloutput: './html/'
          ghpagesbranch: 'main'
          ghpagesdir: './html/'
          
      - name: Generate Issues From TODOs
        uses: alstr/todo-to-issue-action@v4.3
        id: todo
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Clean Up & Report Coverage
        run: "sudo python ./extras/scripts/finish_ci.py"
        shell: bash
